import type { DetectionRule } from "@/lib/rules/types";

export const defaultDetectionRules: DetectionRule[] = [
  {
    id: "timeout",
    name: "Timeout",
    description: "Detect timeout related errors.",
    matchType: "regex",
    pattern: "timeout|timed out|read timed out|sockettimeoutexception",
    flags: "i",
    errorType: "timeout",
    riskLevel: "high",
  },
  {
    id: "connection-refused",
    name: "Connection Refused",
    description: "Detect service or port refusal errors.",
    matchType: "regex",
    pattern: "connection refused|connectexception|refused to connect",
    flags: "i",
    errorType: "connection_refused",
    riskLevel: "high",
  },
  {
    id: "http-5xx",
    name: "HTTP 5xx",
    description: "Detect explicit 5xx HTTP status lines without matching unrelated numbers such as stack frame line numbers or timeouts.",
    matchType: "regex",
    pattern:
      "(?:\\bhttp(?:\\/\\d(?:\\.\\d)?)?\\b[^\\r\\n]{0,24}\\b5\\d\\d\\b|\\bstatus(?:\\s*code)?\\s*[=:]\\s*5\\d\\d\\b|\\bresponse(?:\\s*code)?\\s*[=:]\\s*5\\d\\d\\b|\\bcode\\s*[=:]\\s*5\\d\\d\\b|\\b(?:bad gateway|service unavailable|gateway timeout)\\b)",
    flags: "i",
    errorType: "http_5xx",
    riskLevel: "high",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "http-403",
    name: "HTTP 403",
    description: "Detect 403 forbidden events.",
    matchType: "regex",
    pattern: "\\b403\\b|forbidden",
    flags: "i",
    errorType: "http_403",
    riskLevel: "medium",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "permission-denied",
    name: "Permission Denied",
    description: "Detect permission related failures.",
    matchType: "keyword",
    pattern: "permission denied",
    errorType: "permission_denied",
    riskLevel: "medium",
  },
  {
    id: "generic-exception",
    name: "Exception",
    description: "Detect exception headers, cause lines, or traceback markers.",
    matchType: "regex",
    pattern: "exception|traceback|^caused by:",
    flags: "i",
    errorType: "exception",
    riskLevel: "medium",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "generic-error",
    name: "Generic Error",
    description: "Detect generic error and failed signatures.",
    matchType: "regex",
    pattern: "\\berror\\b|\\bfailed\\b|\\bfailure\\b",
    flags: "i",
    errorType: "generic_error",
    riskLevel: "medium",
  },
  {
    id: "database-error",
    name: "Database Error",
    description: "Detect common database failure signatures.",
    matchType: "regex",
    pattern: "fatal|deadlock|remaining connection slots|too many connections",
    flags: "i",
    errorType: "database_error",
    riskLevel: "high",
    sourceTypes: ["postgres", "application", "custom"],
  },
  {
    id: "fatal-error",
    name: "Fatal Error",
    description: "Detect fatal severity lines.",
    matchType: "regex",
    pattern: "\\bfatal\\b|\\bpanic\\b",
    flags: "i",
    errorType: "fatal_error",
    riskLevel: "high",
  },
];
