import type { DetectionRule } from "@/lib/rules/types";

export const defaultDetectionRules: DetectionRule[] = [
  {
    id: "timeout",
    templateRuleId: "RULE_KEY_003",
    name: "Timeout",
    description: "Detect timeout related errors.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "timeout|timed out|read timed out|sockettimeoutexception",
    flags: "i",
    errorType: "timeout",
    subTags: ["timeout"],
    riskLevel: "high",
  },
  {
    id: "connection-refused",
    templateRuleId: "RULE_KEY_004",
    name: "Connection Refused",
    description: "Detect service or port refusal errors.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "connection refused|connectexception|refused to connect",
    flags: "i",
    errorType: "network_error",
    subTags: ["connection_refused", "db_or_service_call"],
    riskLevel: "high",
  },
  {
    id: "http-5xx",
    templateRuleId: "RULE_REG_001",
    name: "HTTP 5xx",
    description:
      "Detect explicit 5xx HTTP status lines without matching unrelated numbers such as stack frame line numbers or timeouts.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern:
      "(?:\\bhttp(?:\\/\\d(?:\\.\\d)?)?\\b[^\\r\\n]{0,24}\\b5\\d\\d\\b|\\bstatus(?:\\s*code)?\\s*[=:]\\s*5\\d\\d\\b|\\bresponse(?:\\s*code)?\\s*[=:]\\s*5\\d\\d\\b|\\bcode\\s*[=:]\\s*5\\d\\d\\b|\\b(?:bad gateway|service unavailable|gateway timeout)\\b)",
    flags: "i",
    errorType: "service_error",
    subTags: ["http_5xx", "server_error"],
    riskLevel: "high",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "http-403",
    templateRuleId: "RULE_REG_002",
    name: "HTTP 403",
    description: "Detect 403 forbidden events.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "\\b403\\b|forbidden",
    flags: "i",
    errorType: "permission_error",
    subTags: ["http_4xx", "http_403", "client_error"],
    riskLevel: "medium",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "permission-denied",
    templateRuleId: "RULE_KEY_005",
    name: "Permission Denied",
    description: "Detect permission related failures.",
    ruleCategory: "detection",
    matchType: "keyword",
    pattern: "permission denied",
    errorType: "permission_error",
    subTags: ["permission"],
    riskLevel: "medium",
  },
  {
    id: "generic-exception",
    templateRuleId: "RULE_KEY_006",
    name: "Exception",
    description: "Detect exception headers, cause lines, or traceback markers.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "exception|traceback|^caused by:",
    flags: "i",
    errorType: "unknown_error",
    subTags: ["exception", "runtime"],
    riskLevel: "medium",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "generic-error",
    templateRuleId: "RULE_KEY_001",
    name: "Generic Error",
    description: "Detect generic error and failed signatures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "\\berror\\b|\\bfailed\\b|\\bfailure\\b",
    flags: "i",
    errorType: "unknown_error",
    subTags: ["error", "generic", "failed"],
    riskLevel: "medium",
  },
  {
    id: "database-error",
    templateRuleId: "RULE_REG_004",
    name: "Database Error",
    description: "Detect common database failure signatures.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "fatal|deadlock|remaining connection slots|too many connections",
    flags: "i",
    errorType: "database_error",
    subTags: ["db_error_code", "deadlock", "too_many_connections"],
    riskLevel: "high",
    sourceTypes: ["postgres", "application", "custom"],
  },
  {
    id: "fatal-error",
    templateRuleId: "RULE_KEY_008",
    name: "Fatal Error",
    description: "Detect fatal severity lines.",
    ruleCategory: "detection",
    matchType: "regex",
    pattern: "\\bfatal\\b|\\bpanic\\b",
    flags: "i",
    errorType: "service_error",
    subTags: ["fatal", "panic"],
    riskLevel: "high",
  },
];
