import type { DetectionRule } from "@/lib/rules/types";

export const defaultDetectionRules: DetectionRule[] = [
  {
    id: "timeout",
    name: "Timeout",
    description: "Detect timeout related errors.",
    matchType: "keyword",
    pattern: "timeout",
    errorType: "timeout",
    riskLevel: "high",
  },
  {
    id: "connection-refused",
    name: "Connection Refused",
    description: "Detect service or port refusal errors.",
    matchType: "keyword",
    pattern: "connection refused",
    errorType: "connection_refused",
    riskLevel: "high",
  },
  {
    id: "http-5xx",
    name: "HTTP 5xx",
    description: "Detect 5xx HTTP status lines.",
    matchType: "regex",
    pattern: "\\b5\\d\\d\\b",
    errorType: "http_5xx",
    riskLevel: "high",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "http-403",
    name: "HTTP 403",
    description: "Detect 403 forbidden events.",
    matchType: "regex",
    pattern: "\\b403\\b|forbidden",
    flags: "i",
    errorType: "http_403",
    riskLevel: "medium",
    sourceTypes: ["nginx", "application", "custom"],
  },
  {
    id: "permission-denied",
    name: "Permission Denied",
    description: "Detect permission related failures.",
    matchType: "keyword",
    pattern: "permission denied",
    errorType: "permission_denied",
    riskLevel: "medium",
  },
  {
    id: "generic-exception",
    name: "Exception",
    description: "Detect generic exception lines.",
    matchType: "regex",
    pattern: "exception|traceback",
    flags: "i",
    errorType: "exception",
    riskLevel: "medium",
    sourceTypes: ["application", "custom"],
  },
  {
    id: "generic-error",
    name: "Generic Error",
    description: "Detect generic error and failed signatures.",
    matchType: "regex",
    pattern: "\\berror\\b|\\bfailed\\b",
    flags: "i",
    errorType: "generic_error",
    riskLevel: "medium",
  },
  {
    id: "database-error",
    name: "Database Error",
    description: "Detect common database failure signatures.",
    matchType: "regex",
    pattern: "fatal|deadlock|remaining connection slots|too many connections",
    flags: "i",
    errorType: "database_error",
    riskLevel: "high",
    sourceTypes: ["postgres", "application", "custom"],
  },
  {
    id: "fatal-error",
    name: "Fatal Error",
    description: "Detect fatal severity lines.",
    matchType: "regex",
    pattern: "\\bfatal\\b|\\bpanic\\b",
    flags: "i",
    errorType: "fatal_error",
    riskLevel: "high",
  },
];
